[package]
name = "gtk4_test_image"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = "0.9.6"
gstreamer = { version = "0.23" }
gstreamer-base = { version = "0.23" }
gstreamer-video = { version = "0.23"  }
gstreamer-app = { version = "0.23" }
